# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Install Packages and Boost
      run: sudo apt-get update && sudo apt-get install -yq sendmail gnutls-dev libboost-dev libboost-system-dev libcurl4-gnutls-dev

    # Runs a single command using the runners shell
    - name: Build Project
      run: mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=../dist .. && make -j9 && cd ..
      
    - name: Install Project
      run: cd build && make install 
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: dist/*
      
    - uses: act10ns/slack@v1
      with: 
        status: ${{ job.status }}
      if: always()
      env:
        SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
      
